name: Lint workflow
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
    static_analysis:
        runs-on: ubuntu-latest
        steps:
            - name: launching of semgrep
                uses: returntocorp/semgrep-action@v3
    docker_analysis:
        runs-on: ubuntu-latest
        steps:
            - name: launching of hadolint
                uses: hadolint/hadolint@v3
    super_linter:
        runs-on: ubuntu-latest
        if: github.event_name == "pull_request"
        steps:
            - name: launching of super-linter
                uses: github/super-linter@v3